#!/bin/bash
org=rstms
plugin=packer-plugin-vmware
GH_REPO=$org/$plugin
label=x5.0_windows_amd64
git_release=$(git tag -l | head -1)
github_release=$(gh release view --json tagName --jq .tagName)
[[ "$git_release" = "$github_release" ]] && echo 'local release matches' || echo 'needs github release'
exit
binary=${plugin}_${release}_${label}.exe
zipfile=${plugin}_${release}_${label}.zip
checksum=${plugin}_${release}_SHA256SUMS
[ $plugin -nt $binary ] && cp $plugin $binary
[ $binary -nt $zipfile ] && zip $zipfile $binary
[ $zipfile -nt $checksum ] && sha256sum $zipfile >$checksum
gh release upload --clobber $release $zipfile
gh release upload --clobber $release $checksum
