---
name: Bug Report
description: Is something not working as expected? Submit a bug.
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Before filing an issue, please [search the existing issues](https://github.com/vmware/packer-plugin-vmware/issues?q=is%3Aissue+is%3Aopen+label%3Abug) (open or closed), and use the [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) feature to add up-votes to existing issues.

        When filing an issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: The Code of Conduct applies to you when interacting with the community here on GitHub and contributing code.
      options:
        - label: I have read and agree to the [Code of Conduct](https://github.com/vmware/packer-plugin-vmware/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue description to help the maintainers prioritize.
          required: false
        - label: Do not leave "+1" or other comments that do not add relevant information or questions.
          required: false
        - label: If you are interested in working on this issue or have submitted a pull request, please leave a comment.
          required: false
  - type: input
    id: packer-version
    attributes:
      label: Packer Version
      description: Provide the version of Packer you are using.
      placeholder: e.g. x.y.z
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Packer Plugin Version
      description: Provide the version of the Packer plugin you are using.
      placeholder: e.g. x.y.z
    validations:
      required: true
  - type: checkboxes
    id: plugin-component
    attributes:
      label: Plugin Component
      description: Select the plugin component you are using.
      options:
        - label: vmware-iso
          required: false
        - label: vmware-vmx
          required: false
  - type: checkboxes
    id: hypervisor-provider
    attributes:
      label: Hypervisor
      description: Select the hypervisor you are using.
      options:
        - label: VMware Fusion (macOS)
          required: false
        - label: VMware Workstation (Windows/Linux)
          required: false
        - label: VMware ESX (Baremetal)
          required: false
  - type: input
    id: hypervisor-version
    attributes:
      label: Hypervisor Version
      description: Provide the version of the hypervisor you are using.
      placeholder: e.g. YYHX or x.y.z
    validations:
      required: true
  - type: textarea
    id: hypervisor-operating-system
    attributes:
      label: Hypervisor Operating System
      description: Provide the operating system of the hypervisor you are using.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Packer Configuration
      description: |
        - Please provide a code repository, [GitHub Gist](https://gist.github.com/), or simplified code sample suitable for issue reproduction.
        - Please ensure all secrets and identifiable information is removed.
        - Please format any code in code blocks using the markdown editor.

        Learn more about [Code Formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
      placeholder: |
        Please format any code in code blocks using the markdown editor.
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug Output
      description: |
        Please provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete debug output.
      placeholder: |
        Link to a GitHub Gist. Please do not paste the debug output in the issue.
    validations:
      required: true
  - type: textarea
    id: panic
    attributes:
      label: Panic Output
      description: |
        If the plugin produced a panic, please provide a link to a [GitHub Gist](https://gist.github.com/) containing the output of the `crash.log`
      placeholder: |
        Link to a GitHub Gist. Please do not paste the panic output in the issue.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What is it you expected to happen?
        This should be a description of how the functionality you tried to use is supposed to work.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened that's different from the expected behavior?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide any additional information you can provide about the environment.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots of the issue, if applicable.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Please provide any related GitHub issues or pull requests (open or closed) or documentation.
        Learn about [Referencing GitHub Issues](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests).
      placeholder: |
        #0000
    validations:
      required: false